In [2]:
import pandas as pd
import numpy as np
from scipy.optimize import linprog

# Step 1: Read available amounts of ingredients
ingredients_df = pd.read_csv('ingredientslist.csv')
ingredients = ingredients_df.iloc[0].to_numpy()

# Step 2: Read the list of goods the bakery can produce
goods_df = pd.read_csv('goodslist.csv')

# Extract prices and ingredient requirements
prices = goods_df['Price'].to_numpy()
requirements = goods_df[['Yeast', 'Flour', 'Sugar']].to_numpy()

# Step 3: Formulate the linear programming problem
cost = -prices  # Negate prices for maximization
A_ub = requirements.T  # Transpose of requirements for inequality constraints
b_ub = ingredients  # Available ingredients as upper bounds
bounds = [(0, None) for _ in range(len(prices))]  # Non-negative quantities

# Step 4: Solve the linear programming problem
solution = linprog(cost, A_ub=A_ub, b_ub=b_ub, bounds=bounds)

# Step 5: Output the total profit and quantities of each pastry
if solution.success:
    max_profit = -solution.fun  # Negate back to get the maximum profit
    quantities = solution.x
    pastry_names = goods_df['Name'].to_numpy()
    
    print(f"The max profit is {max_profit:.2f} and can be achieved by producing:")
    for pastry_name, quantity in zip(pastry_names, quantities):
        print(f"* {pastry_name}: {quantity:.2f} pieces")
else:
    print("Failed to find a solution.")

The max profit is 449.00 and can be achieved by producing:
* Apple Pie: 50.00 pieces
* Croissant: 0.00 pieces
* Poppy seed roll: 50.00 pieces


In [3]:
A_ub, b_ub, cost

(array([[0.  , 0.5 , 1.15],
        [0.75, 1.5 , 1.5 ],
        [1.5 , 0.25, 0.75]]),
 array([ 57.5, 112.5, 245. ]),
 array([-2.99, -2.5 , -5.99]))